### PR TITLE
New logo, header, and homepage hero image

### PR DESCRIPTION
**Pull request by zarino**
Fixes https://github.com/mysociety/mavc-theme/issues/51

screenshot-2018-6-26 make and browse right to know rti requests

@garethrees is there a staging vhost we can get this deployed to, so the partners can check it out, before we merge?

### CODE REVIEW

**Review by wrightmartin — APPROVED** [review]
👍

**Comment by zarino** [comment]
@garethrees is going to show this to the partners, and check they’re happy before we merge.

**Comment by garethrees** [comment]
[Sent](https://groups.google.com/a/mysociety.org/d/msg/alaveteli/-X2Ee2LxuzE/TWngEbcNAgAJ) – just waiting on feedback.

**Comment by garethrees** [comment]
They like it

**Comment by garethrees** [comment]
🚰 🍷

**Pull request merged**
