### PR TITLE
0.25 upgrade

### PR DESCRIPTION
**Pull request by lizconlan**
Connects to #47

### CODE REVIEW

**Comment by lizconlan** [comment]
Missing help sections

```
theme: mavc-theme locale: en

Missing section: whybother_them in template about
Missing help template:  alaveteli en
Missing help template:  contact en
```

**Comment by lizconlan** [comment]
# Notable visual changes

## Front page

The front page of the site has changed quite a bit since version 0.22.4.9 and currently looks something like this:

screen shot 2016-08-22 at 18 34 35

(I'm really not convinced by my colour choices, I was more focused on getting the layout right.)

**Comment by garethrees** [comment]
Looks like https://github.com/mysociety/mavc-theme/blob/master/lib/model_patches.rb#L11-L14 should be removed too

**Comment by garethrees** [comment]
Looks good.

I'd apply this for the homepage colours:

``` diff
diff --git a/assets/stylesheets/responsive/custom.scss b/assets/stylesheets/responsive/custom.scss
index ef082d3..68d14ef 100644
--- a/assets/stylesheets/responsive/custom.scss
+++ b/assets/stylesheets/responsive/custom.scss
@@ -721,7 +721,7 @@ dt {
   top: auto;
   height: 3.5em;
   width: 3.5em;
-  background-color: darken($color_green, 5%);
+  background-color: darken($color_blue, 5%);
   box-shadow: 0 1px 2px transparentize($color_mavc_midgrey, 0.25);
   padding: 1em;
   border-radius: 100%;
@@ -786,7 +786,7 @@ dt {
   text-decoration: none;
   margin-bottom: 0;
   color: $color_white;
-  background-color: darken($color_orange, 10%);
+  background-color: darken($color_red, 10%);
   transition: background-color 300ms ease-out;

    &:hover, &:focus {
```

This one can get deployed given there are no translations to worry about.

**Comment by lizconlan** [comment]
> Looks like https://github.com/mysociety/mavc-theme/blob/master/lib/model_patches.rb#L11-L14 should be removed too

I'm not so sure - seems to add a line about a specific law to new request preview text.

**Comment by lizconlan** [comment]
## Homepage

liberia-screenshot

## Request page

liberia-request

## Mobile

liberia-mobile

**Pull request merged**
